# Generated by Django 5.1 on 2024-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
