# Generated by Django 5.1 on 2024-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0002_user_dob_user_gender_user_image_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='rto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.IntegerField()),
                ('createpassword', models.CharField(max_length=150)),
                ('repeatepassword', models.CharField(max_length=150)),
                ('rtoimage', models.ImageField(blank=True, null=True, upload_to='rtoimage/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
