# Generated by Django 5.1.2 on 2024-10-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0005_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
