# Generated by Django 5.1.2 on 2024-11-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0007_userroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoute',
        ),
    ]
