# Generated by Django 5.1.2 on 2024-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0008_delete_userroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='to_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
