# Generated by Django 5.0.2 on 2024-11-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0010_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
