# Generated by Django 5.0.2 on 2024-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0013_busconductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='busconductor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='conductor_image/'),
        ),
    ]
