# Generated by Django 5.0.6 on 2024-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0015_buspass_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
